name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3.0
      with:
        apps: scala-cli:0.1.17
    - name: Test
      run: scala-cli test . --cross --require-tests

  publish:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3.0
      with:
        apps: scala-cli:0.1.17
    - name: Release
      run: scala-cli publish . --cross
      env:
        PUBLISH_SECRET_KEY: ${{ secrets.PUBLISH_SECRET_KEY }}
        PUBLISH_SECRET_KEY_PASSWORD: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
        PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
